# Generated by Django 5.0.6 on 2024-06-16 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='time_stamp',
            new_name='timestamp',
        ),
    ]
