# Generated by Django 5.0.6 on 2024-06-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_transaction_is_bankrupt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='is_bankrupt',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
